services:
  # Backend Django API Service
  backend:
    build: ./backend # Path to the backend Dockerfile
    container_name: mill_dash_backend
    command: >
      sh -c "python /app/manage.py makemigrations users &&
            python /app/manage.py makemigrations companies &&
            python /app/manage.py makemigrations timesheets &&
            python /app/manage.py makemigrations invoicing &&
            python /app/manage.py migrate &&
            python /app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/api/:/app/ # Mounts the local code into the container for live-reloading
    ports:
      - "8000:8000" # Exposes port 8000 to host machine
    env_file:
      - ./.env # Loads environment variables from the .env file
    depends_on:
      db: # Ensures the database is started and healthy before the backend
        condition: service_healthy

  # Frontend React Service
  frontend:
    build: ./frontend # Path to the frontend Dockerfile
    container_name: mill_dash_frontend
    ports:
      - "3000:80" # Exposes the React dev server port
    stdin_open: true
    tty: true

  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine # Use the official PostgreSQL image
    container_name: mill_dash_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # Persists database data
    env_file:
      - ./.env # Loads database credentials from the .env file
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  postgres_data: # Defines the named volume for data persistence